services:
  hello-service:
    build: ./hello-service
    container_name: hello-service

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - hello-service
    environment:
      - HELLO_SERVICE_URL=http://hello-service:3000
